### PR TITLE
Rebuild for dolfinx 0.9

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Review by finsberg — APPROVED** [review]

**Comment by finsberg** [comment]
@minrk If you think this looks OK then feel free to merge. I just updated the versions, sha and added `packaging` as a new dependency. Also, I had to rerun two of the pipelines and they succeeded the second time without any changes, so don't know what is going on there. Maybe some of these builds are a bit flaky.

**Comment by minrk** [comment]
Thanks! Do you want to have builds for both 0.8 and 0.9? Because we can do that (it will be a lot of builds!)

**Comment by finsberg** [comment]
My opinion would be to only build for the latest stable version of dolfinx and therefore don't build for 0.8, but I will let @jorgensd have the final say on this.

**Comment by jorgensd** [comment]
> My opinion would be to only build for the latest stable version of dolfinx and therefore don't build for 0.8, but I will let @jorgensd have the final say on this.

I don’t think we need a rebuild for 0.8. 
idea would be that new features are supported one version back.

**Pull request merged**
